# Generated by Django 2.1.7 on 2021-01-08 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210108_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 8, 17, 43, 11, 451888)),
        ),
    ]
